### PR TITLE
Fix algo name

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by stephane-caron** [comment]
True, but can't Douglas-Rachford be interpreted as an Augmented Lagrangian method?

Here is a piece I found doing some background research on this:

> ... relatively old methods which appeared as early as the fifties with Douglas- and Peaceman-Rachford algorithms for linear operators. As these techniques can be interpreted as separable versions of the Augmented Lagrangian dual methods, their main benefit is the regularization effect of the proximal steps which induce numerical stability and smoothness of the implicit primal and dual value functions. 

Source: https://hal.archives-ouvertes.fr/hal-01691690/document

**Comment by stephane-caron** [comment]
For the benchmark I think it makes sense to have more precise labels in the Algorithms column :+1: 

Meanwhile, the [Algorithms column on qpsolvers](https://github.com/stephane-caron/qpsolvers#solvers) is for less expert users. The goal there is to cluster solvers by methods, with as few clusters as possible. So if it is correct that Douglas-Rachford is also augmented Lagrangian then it is a better label for there.

**Comment by jcarpent** [comment]
> Thank you for pointing this out! It is true, but can't Douglas-Rachford be interpreted as an Augmented Lagrangian method?
> 
> Here is a piece I found doing some background research on this:
> 
> > ... relatively old methods which appeared as early as the fifties with Douglas- and Peaceman-Rachford algorithms for linear operators. As these techniques can be interpreted as separable versions of the Augmented Lagrangian dual methods, their main benefit is the regularization effect of the proximal steps which induce numerical stability and smoothness of the implicit primal and dual value functions.
> 
> Source: https://hal.archives-ouvertes.fr/hal-01691690/document

Yes, but being precise helps a lot to make the distinction. Otherwise, people will likely interpret all the solutions as the same.

**Comment by jcarpent** [comment]
At this level, you might be also able to recast IP as Auglag methods.

**Comment by jcarpent** [comment]
Auglag family might contain first-order or second-order methods.
Most of the time, ADMM or DR methods behave as first-order methods ...

**Comment by jcarpent** [comment]
In general, I think precise nomenclature helps the community to dive into the topics.
There are too many scientific communications which introduce confusion. It is time to correct it.

**Comment by stephane-caron** [comment]
Fair enough. The community for this benchmark is more expert, so I agree with moving to more precise labels.

**Pull request merged**
